-- 코드를 작성해주세요
SELECT dep.DEPT_ID, dep.DEPT_NAME_EN, ROUND(AVG(emp.SAL))AVG_SAL 
FROM HR_DEPARTMENT AS dep JOIN HR_EMPLOYEES AS emp ON dep.DEPT_ID = emp.DEPT_ID
GROUP BY dep.DEPT_NAME_EN
ORDER BY AVG_SAL DESC